name: Semgrep SAST Scan

on:
  push:
    branches:
      - '**'   

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: semgrep scan --config=auto --verbose
